"use client";

import { useEffect, useRef, useState, type FormEvent } from "react";
import { ApiError, createEvaluationBatch, getCasePage, getEvaluationPage, type CasePage, type EvaluationPage, type JsonRecord } from "@/lib/api";
import { formatTime } from "./case-worklist";
import { caseLink } from "./operations-overview";

function text(value: unknown, fallback = "") { return typeof value === "string" || typeof value === "number" ? String(value) : fallback; }
export function EvaluationsPanel({ workspaceId, token, roles, onAccessFailure }: { workspaceId: string; token: string; roles: string[]; onAccessFailure: () => void }) {
  const [batches, setBatches] = useState<JsonRecord[]>([]); const [cases, setCases] = useState<CasePage | null>(null); const [page, setPage] = useState(1); const [selected, setSelected] = useState<string[]>([]); const [repeats, setRepeats] = useState(1); const [reason, setReason] = useState(""); const [confirmed, setConfirmed] = useState(false); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [refresh, setRefresh] = useState(0); const [activeBatch, setActiveBatch] = useState("");
  const request = useRef<AbortController | null>(null);
  const [batchPage, setBatchPage] = useState(1);
  const [batchResult, setBatchResult] = useState<EvaluationPage | null>(null);
  const [batchLoading, setBatchLoading] = useState(false);
  const [batchError, setBatchError] = useState("");
  const [hasMoreBatches, setHasMoreBatches] = useState(false);
  const [lookupBatch, setLookupBatch] = useState("");
  const [resultScope, setResultScope] = useState("");
  const batchScope = `${workspaceId}:${token}:${activeBatch}:${batchPage}`;
  const visibleBatch = resultScope === batchScope ? batchResult : null;
  function chooseBatch(id: string) { setActiveBatch(id); setBatchPage(1); }
  useEffect(() => {
    const controller = new AbortController(); setBatchResult(null); setBatchError(""); setBatchLoading(Boolean(activeBatch));
    if (!activeBatch) return () => controller.abort();
    getEvaluationPage(workspaceId, activeBatch, batchPage, token, controller.signal).then(result => { if (!controller.signal.aborted) { setBatchResult(result); setResultScope(batchScope); setBatchLoading(false); } }).catch(failure => { if (!controller.signal.aborted) { setBatchResult(null); setBatchLoading(false); setBatchError(failure instanceof Error ? failure.message : "The selected batch could not be read."); if (failure instanceof ApiError && [401, 403].includes(failure.status)) onAccessFailure(); } });
    return () => controller.abort();
  }, [workspaceId, token, activeBatch, batchPage, refresh]);
  useEffect(() => {
    const controller = new AbortController(); request.current = controller; setLoading(true); setError(""); setBatches([]); setCases(null);
    Promise.all([getEvaluationPage(workspaceId, "", 1, token, controller.signal), getCasePage(workspaceId, page, {}, token, controller.signal)]).then(([items, casePage]) => { if (!controller.signal.aborted) { setBatches(items.batches); setHasMoreBatches(items.has_more_batches); setCases(casePage); setLoading(false); } }).catch(failure => { if (!controller.signal.aborted) { setLoading(false); setBatches([]); setCases(null); setError(failure instanceof Error ? failure.message : "Evaluation data could not be read."); if (failure instanceof ApiError && [401, 403].includes(failure.status)) { setSelected([]); onAccessFailure(); } } });
    return () => controller.abort();
  }, [workspaceId, token, page, refresh]);
  useEffect(() => () => request.current?.abort(), []);
  const active = visibleBatch?.batches[0];
  const hasActive = batches.some(item => { const states = item.run_states && typeof item.run_states === "object" ? item.run_states as JsonRecord : {}; return Number(states.queued || 0) + Number(states.running || 0) > 0; });
  useEffect(() => { if (!hasActive || busy) return; const interval = window.setInterval(() => setRefresh(value => value + 1), 5000); return () => window.clearInterval(interval); }, [hasActive, busy]);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); if (busy || !confirmed || !selected.length || !roles.includes("process_owner")) return;
    const controller = new AbortController(); request.current = controller; setBusy(true); setError(""); setNotice("");
    try { const result = await createEvaluationBatch(workspaceId, selected, repeats, reason.trim(), token, controller.signal); if (!controller.signal.aborted) { setNotice(result.paid_dispatch_enabled === false ? "Evaluation batch saved. Paid model dispatch is disabled; the batch is queued until the administrator enables it." : "Evaluation batch saved. Completion and quality review remain separate."); chooseBatch(text(result.id || result.batch_id)); setConfirmed(false); setRefresh(value => value + 1); } }
    catch (failure) { if (!controller.signal.aborted) { setError(failure instanceof Error ? failure.message : "The evaluation batch could not be saved."); if (failure instanceof ApiError && [401, 403].includes(failure.status)) { setCases(null); setBatches([]); setSelected([]); onAccessFailure(); } } }
    finally { if (!controller.signal.aborted) setBusy(false); }
  }
  return <section className="operations-section"><div className="section-header"><div><h2>Evaluation batches</h2><p>Compare saved case runs with repeat counts, usage and reviewable outcomes.</p></div><button className="button button-secondary" disabled={busy || loading} type="button" onClick={() => setRefresh(value => value + 1)}>Refresh results</button></div><p className="workflow-notice">Each batch uses durable budget controls and automatic Arize logging. Model execution must be enabled by the administrator before dispatch. Software checks alone do not establish model quality.</p>{error && <p className="inline-error" role="alert">{error}</p>}{notice && <p className="workflow-success" role="status">{notice}</p>}{loading && <p className="section-intro" role="status">Loading cases and saved evaluation batches…</p>}
    {roles.includes("process_owner") && cases && <details className="evaluation-create"><summary>Prepare a model evaluation batch</summary><form className="workflow-form" onSubmit={submit}><fieldset className="citation-choices"><legend>Cases in the batch ({selected.length} selected)</legend>{cases.items.map(item => <label className="attestation" key={item.id}><input type="checkbox" disabled={busy || loading || (!selected.includes(item.id) && selected.length >= 20)} checked={selected.includes(item.id)} onChange={event => { setSelected(previous => event.target.checked ? [...previous, item.id] : previous.filter(id => id !== item.id)); setConfirmed(false); }} /><span>{item.title}<small>{item.id}</small></span></label>)}{!cases.items.length && <p className="field-help">Save cases before preparing a batch.</p>}</fieldset><div className="pagination"><button className="button button-secondary" type="button" disabled={page <= 1 || busy || loading} onClick={() => setPage(value => value - 1)}>Previous cases</button><span>Page {page} · {cases.total} cases</span><button className="button button-secondary" type="button" disabled={page * cases.page_size >= cases.total || busy || loading} onClick={() => setPage(value => value + 1)}>Next cases</button></div><label>Repeats per case<select value={repeats} disabled={busy} onChange={event => { setRepeats(Number(event.target.value)); setConfirmed(false); }}><option value={1}>1</option><option value={2}>2</option><option value={3}>3</option></select></label><label>Experiment purpose and review criteria<textarea required maxLength={1000} rows={3} disabled={busy} value={reason} onChange={event => { setReason(event.target.value); setConfirmed(false); }} /></label><label className="attestation"><input type="checkbox" required checked={confirmed} disabled={busy || !selected.length} onChange={event => setConfirmed(event.target.checked)} /><span>I reviewed the selected case evidence and confirm this bounded evaluation request ({selected.length * repeats} planned runs).</span></label><button className="button button-primary" type="submit" disabled={busy || loading || !confirmed || !selected.length}>{busy ? "Saving…" : "Request evaluation batch"}</button></form></details>}
    <p className="field-help">Latest 20 accessible batches{hasMoreBatches ? "; older batches are available by ID" : ""}. Run summaries cover each listed batch; full outputs are paginated after selection.</p><form className="knowledge-search" onSubmit={event => { event.preventDefault(); chooseBatch(lookupBatch.trim()); }}><label>Open batch ID<input value={lookupBatch} required maxLength={36} disabled={busy} onChange={event => setLookupBatch(event.target.value)} /></label><button className="button button-secondary" type="submit" disabled={busy}>Open saved batch</button></form><div className="knowledge-layout"><div className="knowledge-list">{batches.map((item, index) => <button type="button" className={item.id === activeBatch ? "knowledge-entry selected" : "knowledge-entry"} key={text(item.id, String(index))} onClick={() => chooseBatch(text(item.id))} disabled={busy}><span>{`${text(item.total_runs, "0")} planned runs`}</span><strong>{text(item.reason, "Evaluation batch")}</strong><small>{formatTime(typeof item.created_at === "string" ? item.created_at : null)} · {text(item.repeats, "1")} repeats · {JSON.stringify(item.run_states || {})}</small></button>)}{!loading && !batches.length && <p className="section-intro">No model evaluation batches have been saved.</p>}</div><div className="knowledge-detail">{batchLoading && <p className="field-help" role="status">Loading selected batch outputs…</p>}{batchError && <p className="inline-error" role="alert">{batchError}</p>}{active && visibleBatch ? <><h3>Saved batch results</h3><p className="field-help">Inspect actual outputs, failed runs and usage. Human semantic review remains required before quality or publication claims.</p>{Array.isArray(active.case_ids) && <ul className="source-file-list">{active.case_ids.filter(id => typeof id === "string").map(id => <li key={id}><a href={caseLink(workspaceId, id)} target="_blank" rel="noopener noreferrer">Open case {id}</a></li>)}</ul>}<p className="snapshot-caption">{visibleBatch.total_runs} runs in this batch · page {visibleBatch.page} of {Math.max(1, Math.ceil(visibleBatch.total_runs / visibleBatch.page_size))}. Live paginated read; refresh if runs change during loading.</p><pre className="source-content">{JSON.stringify({ batch: active, runs_on_this_page: visibleBatch.runs, stage_calls_on_this_page: visibleBatch.stage_calls }, null, 2)}</pre><div className="pagination"><button type="button" className="button button-secondary" disabled={batchLoading || batchPage <= 1} onClick={() => setBatchPage(value => value - 1)}>Previous runs</button><span>{visibleBatch.runs.length} runs on this page</span><button type="button" className="button button-secondary" disabled={batchLoading || !visibleBatch.has_more_runs} onClick={() => setBatchPage(value => value + 1)}>Next runs</button></div></> : <p className="section-intro">Select a batch to inspect its saved runs and results.</p>}</div></div>
  </section>;
}
