"use client";

import Link from "next/link";
import { useState } from "react";
import type { CaseDetail, FactualEntry, FactualResult } from "@/lib/api";
import { previewCases } from "@/lib/design-preview";
import { CaseWorklist } from "./case-worklist";
import { FactualCaseContent } from "./factual-case";
import { WorkspaceShell } from "./workspace-shell";
import { Icon } from "./icon";

const original = previewCases[0].evidence.find(item => item.name.endsWith(".log"))?.content || previewCases[0].evidence[0].content;
const lines = original.split("\n");
const baseEntry: FactualEntry = { entry_id: "demo-message", source_id: "demo-original", source_version: "1", source_span: { line_start: 11, line_end: 13 }, kind: "message", raw_text: lines.slice(10, 13).join("\n") + "\n", fields: [], ambiguity: null };
const stopEntry: FactualEntry = { ...baseEntry, entry_id: "demo-stop", source_span: { line_start: 14, line_end: 17 }, raw_text: lines.slice(13, 17).join("\n") + "\n" };
const summary: FactualResult = { result_kind: "factual", outcome: "completed", extraction: { entries: [baseEntry, stopEntry], extraction_limitations: ["This hand-authored interface illustration includes two extracted entries. It is not a model evaluation."] }, summary: { title: { text: "Target lookup failed for G/L account 0041001000", supporting_entry_ids: [baseEntry.entry_id] }, statements: [{ text: "The supplied log reports that target G/L account 0041001000 could not be located for chart SYN1 in CFIN-DEMO/100.", supporting_entry_ids: [baseEntry.entry_id] }, { text: "The target posting stopped for this attempt; no target document reference was returned.", supporting_entry_ids: [stopEntry.entry_id] }], unresolved_details: [{ text: "Evidence is limited to this attempt. The error wording does not establish a confirmed cause.", supporting_entry_ids: [stopEntry.entry_id] }], related_cases: [] }, limitations: ["This hand-authored interface illustration includes two extracted entries. It is not a model evaluation."], history: { status: "not_searched" } };
const demoCase: CaseDetail["case"] = { id: "preview-factual-md01", title: summary.summary!.title.text, description: "Supplied original observations", priority: "P2", status: "created", diagnosis_status: "needs_review", created_at: "2026-10-02T09:00:00Z", due_at: null, version: 1, workflow_version: "log-only-v1", result_kind: "factual", factual_review_status: "pending_review", analysis_status: "available", factual_result: summary, published_run_id: "demo-run", requested_run_id: "demo-run" };
const baseDetail: CaseDetail = { case: demoCase, factual_result: summary, evidence: [{ id: "preview-original", kind: "original_log", filename: "original-log.txt", content_type: "text/plain", source_id: "demo-original", source_version: "1" }], runs: [{ id: "demo-run", state: "succeeded", created_at: "2026-10-02T09:00:00Z" }], references: [], attempts: [], milestones: [], validations: [], activity: [], reviews: [] };
export default function FactualPreview() {
  const [state, setState] = useState("available");
  const detail: CaseDetail = { ...baseDetail, case: { ...demoCase, analysis_status: state, ...(state !== "available" ? { requested_run_id: "demo-new-run" } : {}) }, runs: state === "available" ? baseDetail.runs : [{ id: "demo-new-run", state: state === "failed" ? "failed" : "running", error_code: state === "failed" ? "The summary step did not complete within its limit." : null }, ...baseDetail.runs] };
  return <WorkspaceShell preview><div className="page-heading"><div><div className="breadcrumb">Operations <span>/</span> Factual case preview</div><h1>Case board</h1><p>Read the facts, check the original, record the investigation.</p></div><Link className="button button-secondary" href="/preview">Legacy examples</Link></div><div className="connection-banner preview-banner"><Icon name="preview" size={19} /><p><strong>Synthetic interface illustration</strong><span>Hand-authored factual content. No model run, human approval or cloud case is claimed.</span></p></div><div className="factual-preview-toolbar"><label>Display state <select aria-label="Preview analysis state" value={state} onChange={event => setState(event.target.value)}><option value="available">Available</option><option value="needs_refresh">Older summary / running</option><option value="failed">Failed replacement</option></select></label></div><CaseWorklist items={[detail.case]} preview detailRenderer={() => <><div className="detail-heading"><div className="detail-eyebrow">Factual case · synthetic illustration</div><h2>{detail.case.title}</h2><p>Pending human review</p></div><div className="detail-content">{state === "needs_refresh" && <p className="workflow-notice" role="status">Analysis running. This earlier summary remains visible with its original evidence.</p>}<FactualCaseContent detail={detail} workspaceId="preview" token="" previewOriginals={{ "preview-original": original }} /></div></>} /></WorkspaceShell>;
}
