"use client";

import { useState } from "react";
import type { CaseDetail, FactualEntry, FactualResult, FactualStatement, JsonRecord } from "@/lib/api";
import { EvidenceViewer } from "./case-workflow";
import { formatTime } from "./case-worklist";

export function isFactualCase(detail: CaseDetail): boolean { return detail.case.workflow_version === "log-only-v1" || detail.case.result_kind === "factual"; }
export function factualResult(detail: CaseDetail): FactualResult | null {
  const candidate = detail.factual_result ?? detail.case.factual_result;
  return candidate && typeof candidate === "object" && "result_kind" in candidate && candidate.result_kind === "factual" ? candidate as FactualResult : null;
}
function text(value: unknown, fallback = "Not recorded") { return typeof value === "string" || typeof value === "number" ? String(value) : fallback; }
export function FactualCaseContent({ detail, workspaceId, token, previewOriginals }: { detail: CaseDetail; workspaceId: string; token: string; previewOriginals?: Record<string, string> }) {
  const result = factualResult(detail);
  const summary = result?.summary;
  const title = summary?.title ?? result?.title;
  const statements = summary?.statements ?? result?.statements ?? [];
  const unresolved = summary?.unresolved_details ?? result?.unresolved_details ?? [];
  const related = summary?.related_cases ?? result?.related_cases ?? [];
  const entries = result?.extraction?.entries ?? [];
  const sources = detail.evidence.filter(item => item.kind === "original_log" || item.kind === "original" || entries.some(entry => entry.source_id === item.source_id && entry.source_version === item.source_version));
  const [opened, setOpened] = useState<string[]>([]);
  const [focus, setFocus] = useState<{ evidenceId: string; lineStart: number; lineEnd: number; navigationKey: number } | null>(null);
  const latestRequested = detail.runs.find(run => run.id === detail.case.requested_run_id) || detail.runs[0];
  const stale = ["stale", "superseded", "needs_refresh"].includes(text(detail.case.analysis_status, "")) || Boolean(result && detail.case.published_run_id && detail.case.requested_run_id && detail.case.published_run_id !== detail.case.requested_run_id);
  const historyStatus = result?.history_retrieval_status ?? result?.history?.status ?? "not_searched";
  const historyLimitation = result?.history_retrieval_limitation ?? result?.history?.limitation;
  function showEntry(entry: FactualEntry) {
    const source = detail.evidence.find(item => item.source_id === entry.source_id && item.source_version === entry.source_version);
    if (!source) return;
    const id = String(source.id);
    setOpened(previous => [...new Set([...previous, id])]);
    setFocus(previous => ({ evidenceId: id, lineStart: entry.source_span.line_start, lineEnd: entry.source_span.line_end, navigationKey: (previous?.navigationKey ?? 0) + 1 }));
  }
  function references(ids: string[]) { return <span className="factual-citations">{ids.map(id => { const entry = entries.find(item => item.entry_id === id); if (!entry) return <span className="field-help" key={id}>Source unavailable</span>; const source = detail.evidence.find(item => item.source_id === entry.source_id && item.source_version === entry.source_version); return <button className="citation-link" type="button" key={id} disabled={!source} onClick={() => showEntry(entry)} aria-label={`Open ${text(source?.filename, entry.source_id)}, version ${entry.source_version}, lines ${entry.source_span.line_start} to ${entry.source_span.line_end}`}>{text(source?.filename, entry.source_id)} · v{entry.source_version} · L{entry.source_span.line_start}{entry.source_span.line_end !== entry.source_span.line_start ? `–${entry.source_span.line_end}` : ""}</button>; })}</span>; }
  function statement(item: FactualStatement, index: number) { return <li key={index}><p>{item.text}</p>{references(item.supporting_entry_ids)}</li>; }
  return <>
    {stale && <p className="workflow-notice" role="status">This summary is from an earlier analysis. Review the current originals; a newer request has not published a replacement.</p>}
    {latestRequested?.state === "failed" && <p className="inline-error" role="alert">The latest analysis failed. {text(latestRequested.error_code, "A factual summary could not be completed.")} Original evidence remains available.</p>}
    <section className="detail-section factual-brief"><h3>Factual summary</h3>{result && title ? <>{references(title.supporting_entry_ids)}<ul className="factual-statements">{statements.map(statement)}</ul></> : <p className="section-intro">{result?.failure_reason || "No factual summary is available yet. The supplied originals are preserved below."}</p>}<p className="field-help">Human review: {text(detail.case.factual_review_status, "Pending").replaceAll("_", " ")}. These observations describe the supplied logs.</p></section>
    {(unresolved.length > 0 || Boolean(result?.limitations?.length)) && <section className="detail-section"><h3>Uncertainty and limitations</h3>{unresolved.length > 0 && <ul className="factual-statements">{unresolved.map(statement)}</ul>}{Boolean(result?.limitations?.length) && <ul className="factual-limitations">{result?.limitations.map((item, index) => <li key={index}>{item}</li>)}</ul>}</section>}
    <section className="detail-section"><h3>Related reviewed cases</h3><p className="field-help">Historical findings are attributed to their original case. They do not establish a cause for this case.</p>{related.length ? related.map(reference => <article className="related-case" key={`${reference.case_id}:${reference.knowledge_id}:${reference.knowledge_version}`}><a href={`/?workspace_id=${encodeURIComponent(workspaceId)}&case_id=${encodeURIComponent(reference.case_id)}`} target="_blank" rel="noopener noreferrer">Open reviewed case {reference.case_id}</a><p className="field-help">Reviewed version {reference.knowledge_version} · access is rechecked when opened</p>{reference.historical_note && <p>{reference.historical_note}</p>}<h4>Matching details</h4><ul>{reference.matching_details.map((item, index) => <li key={index}>{item}</li>)}</ul>{reference.differing_details.length > 0 && <><h4>Differences</h4><ul>{reference.differing_details.map((item, index) => <li key={index}>{item}</li>)}</ul></>}{references(reference.current_entry_ids)}<ul className="source-file-list">{reference.historical_citations.map((citation: JsonRecord, index) => <li key={index}><a href={`/?workspace_id=${encodeURIComponent(workspaceId)}&case_id=${encodeURIComponent(reference.case_id)}&source_id=${encodeURIComponent(text(citation.source_id, ""))}&source_version=${encodeURIComponent(text(citation.source_version, ""))}&line_start=${Number(citation.line_start || 0)}&line_end=${Number(citation.line_end || 0)}`} target="_blank" rel="noopener noreferrer">Historical source {text(citation.source_id)} · v{text(citation.source_version)} · {citation.record_id ? text(citation.record_id) : `L${text(citation.line_start)}–${text(citation.line_end)}`}</a></li>)}</ul></article>) : <p className="section-intro">{historyStatus === "completed" ? "The history search completed. No related case is cited in this summary." : historyStatus === "unavailable" ? "Reviewed history could not be loaded." : "Reviewed history has not been searched for this result."}</p>}{historyLimitation && <p className="workflow-notice">{historyLimitation}</p>}</section>
    <section className="detail-section"><h3>Complete original logs</h3><p className="field-help">Expand any original to read every saved line or download the unchanged file. Highlighted line numbers are inclusive.</p>{sources.length ? sources.map(source => { const id = String(source.id); return <details className="original-section" id={`original-${id}`} key={id} open={opened.includes(id)} onToggle={event => { const open = event.currentTarget.open; setOpened(previous => open ? [...new Set([...previous, id])] : previous.filter(item => item !== id)); }}><summary>{text(source.filename)} · version {text(source.source_version)}</summary>{opened.includes(id) && <EvidenceViewer evidence={source} workspaceId={workspaceId} token={token} previewContent={previewOriginals?.[id]} lineRange={focus?.evidenceId === id ? { start: focus.lineStart, end: focus.lineEnd, navigationKey: focus.navigationKey } : undefined} />}</details>; }) : <p className="section-intro">No original source is registered in this view. Refresh the case to check access.</p>}</section>
    <section className="detail-section"><details className="analysis-output"><summary>Full extraction · {entries.length} entries</summary><p className="field-help">All saved extracted entries are shown here, including entries not selected for the brief. The originals above remain authoritative.</p>{entries.map(entry => <article className="extraction-entry" key={entry.entry_id}><h4>{entry.kind.replaceAll("_", " ")}</h4>{references([entry.entry_id])}<pre className="source-content">{entry.raw_text}</pre>{entry.fields.length > 0 && <dl className="context-grid">{entry.fields.map((field, index) => <div key={index}><dt>{field.name_as_logged}</dt><dd>{field.value_as_logged}{field.context_as_logged && <small> · {field.context_as_logged}</small>}</dd></div>)}</dl>}{entry.ambiguity && <p className="workflow-notice">{entry.ambiguity}</p>}</article>)}{entries.length > 0 && <details><summary>Inspect every saved extraction field</summary><pre className="source-content">{JSON.stringify(result?.extraction, null, 2)}</pre></details>}{!entries.length && <p className="section-intro">No extraction has been saved.</p>}</details></section>
    <section className="detail-section"><h3>Human investigation and review</h3><p className="field-help">Human findings and actions are separate from the observations in the original logs.</p>{(detail.reviews || []).map((review, index) => <article key={text(review.id, String(index))} className="human-record"><strong>{text(review.decision, "Review")}</strong><p>{text(review.reason, "")}</p>{Boolean(review.findings) && <pre className="source-content">{JSON.stringify(review.findings, null, 2)}</pre>}</article>)}{detail.milestones.map((milestone, index) => <article className="human-record" key={text(milestone.id, String(index))}><strong>{text(milestone.kind).replaceAll("_", " ")}</strong><time>{formatTime(typeof milestone.action_at === "string" ? milestone.action_at : null)}</time><p>{text(milestone.reason ?? milestone.findings ?? milestone.explanation, "")}</p><details><summary>Saved human record</summary><pre className="source-content">{JSON.stringify(milestone, null, 2)}</pre></details></article>)}{Boolean(detail.resolution_records?.length) && <details className="analysis-output"><summary>Completed resolution records and IDs for knowledge review</summary><pre className="source-content">{JSON.stringify(detail.resolution_records, null, 2)}</pre></details>}{!(detail.reviews?.length || detail.milestones.length) && <p className="section-intro">No human findings or review have been recorded.</p>}</section>
  </>;
}
