-- Record failures without a model result; preserve exact binding checks for outputs.
begin;
create or replace function private.error_analysis_complete_run(p jsonb) returns jsonb language plpgsql security definer set search_path='' as $$
#variable_conflict use_variable
declare job public.jobs; run public.analysis_runs; c public.cases; receipt public.run_results; output jsonb:=p->'output'; succeeded boolean:=coalesce((p->>'succeeded')::boolean,false); current_run boolean;
begin
 select * into job from public.jobs where id=(p->>'job_id')::uuid for update; if not found then raise sqlstate 'PT404' using message='Job not found'; end if;
 select * into run from public.analysis_runs where id=job.run_id for update; if run.workflow_version<>'error-analysis-v1' then raise sqlstate 'PT422' using message='Error Analysis run required'; end if;
 select * into receipt from public.run_results where job_id=job.id and submitted_lease_token=(p->>'lease_token')::uuid; if found then return jsonb_build_object('run_id',receipt.run_id,'promoted',receipt.promoted,'duplicate',true); end if;
 insert into public.run_results(workspace_id,run_id,job_id,submitted_lease_token,output,succeeded) values(job.workspace_id,job.run_id,job.id,(p->>'lease_token')::uuid,output,succeeded) returning * into receipt;
 select * into job from private.require_lease(job.id,(p->>'lease_token')::uuid); select * into c from public.cases where id=run.case_id for update;
 if output is not null and output<>'null'::jsonb and ((select jsonb_object_agg(k,output->k) from jsonb_object_keys(run.snapshot->'binding') k) is distinct from run.snapshot->'binding' or output->>'result_kind' is distinct from 'error_analysis' or output->'source_manifest' is distinct from run.snapshot->'source_manifest') then raise sqlstate 'PT422' using message='Error Analysis result binding mismatch'; end if;
 if succeeded and (output->>'outcome' is distinct from 'completed' or not exists(select 1 from public.validated_stages s where s.run_id=run.id and s.stage='agent1' and invalidated_at is null) or not exists(select 1 from public.validated_stages s where s.run_id=run.id and s.stage='agent2' and invalidated_at is null) or not exists(select 1 from public.validated_stages s where s.run_id=run.id and s.stage='agent3' and invalidated_at is null) or output->'extraction' is distinct from (select s.output->'output' from public.validated_stages s where s.run_id=run.id and s.stage='agent1' and s.invalidated_at is null) or (output->'analysis') - 'route' is distinct from (select s.output->'output' from public.validated_stages s where s.run_id=run.id and s.stage='agent2' and s.invalidated_at is null) or output->'case_content' is distinct from (select s.output->'output' from public.validated_stages s where s.run_id=run.id and s.stage='agent3' and s.invalidated_at is null) or exists(select 1 from public.stage_calls where run_id=run.id and (state in ('reserved','in_flight','usage_unknown') or actual_usd is null))) then raise sqlstate 'PT422' using message='Validated Error Analysis stages and reconciled usage required'; end if;
 current_run:=not run.evaluation_only and c.linked_case_id is null and c.current_attempt_id=run.attempt_id and c.input_revision=run.input_revision and c.requested_run_id=run.id;
 update public.analysis_runs set state=case when run.evaluation_only then case when succeeded then 'succeeded' else 'failed' end when current_run and succeeded then 'succeeded' when current_run then 'failed' else 'historical' end,output=output,error_code=p->>'error_code' where id=run.id;
 if current_run then update public.cases set analysis_status=case when succeeded then 'available' else 'unavailable' end,published_run_id=case when succeeded then run.id else published_run_id end,error_analysis_result=case when succeeded or published_run_id is null then output else error_analysis_result end,category=case when succeeded then output->'analysis'->>'category_id' else category end,title=case when succeeded then output->'case_content'->'title'->>'text' else title end,description=case when succeeded then coalesce((select string_agg(x->>'text',E'\n') from jsonb_array_elements(output->'case_content'->'what_happened') x),'') else description end,route_policy_id=case when succeeded then (output->'analysis'->'route'->>'policy_id')::uuid else route_policy_id end,route_policy_version=case when succeeded then (output->'analysis'->'route'->>'policy_version')::integer else route_policy_version end,route_state=case when succeeded then 'not_started' else route_state end,version=version+1 where id=c.id; end if;
 update public.jobs set state=case when succeeded then 'succeeded' else 'failed' end,lease_until=null,lease_token=null where id=job.id; update private.worker_slot set job_id=null,lease_token=null,lease_until=null where singleton=1 and job_id=job.id and lease_token=job.lease_token; update public.run_results set promoted=current_run where id=receipt.id;
 return jsonb_build_object('run_id',run.id,'promoted',current_run);
end $$;
commit;
